# Generated by Django 5.1.13 on 2025-10-04 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventopage',
            name='categoria',
        ),
    ]
