# Generated by Django 5.1.13 on 2025-10-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_eventoindexpage_delete_eventosindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopage',
            name='color',
            field=models.CharField(default='#007bff', help_text='Selecciona un color en formato HEX (por ejemplo: #FF5733)', max_length=7),
        ),
    ]
