# Generated by Django 5.1.13 on 2025-10-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_eventopage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaevento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
