# Generated by Django 5.1.13 on 2025-10-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_categoriaevento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaevento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
