# Generated by Django 5.1.13 on 2025-10-05 17:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descripcion', wagtail.fields.RichTextField(blank=True)),
                ('elementos', wagtail.fields.StreamField([('multimedia', 4)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('imagen', 'Imagen'), ('video', 'Video (YouTube, Vimeo, etc.)')], 'label': 'Tipo de medio'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL del video (YouTube, Vimeo, etc.)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Descripción breve del contenido', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('tipo', 0), ('imagen', 1), ('video_url', 2), ('descripcion', 3)]], {})}, verbose_name='Galería de medios')),
            ],
            options={
                'verbose_name': 'Galería Multimedia',
                'verbose_name_plural': 'Galerías Multimedia',
            },
            bases=('wagtailcore.page',),
        ),
    ]
