# Generated by Django 5.1.13 on 2025-10-06 13:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='carrusel',
            field=wagtail.fields.StreamField([('imagen', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True})}),
        ),
    ]
