# Generated by Django 5.1.13 on 2025-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='deporte',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('basquet', 'Basquet'), ('voley', 'Voley'), ('handball', 'Handball')], default='futbol', max_length=20),
        ),
    ]
